#!/usr/bin/env python
import importlib.util
import sys
import os

Import("env")
Import("env_modules")

def is_v8_available():
    return env["platform"] != "web"
    # return env["platform"] == "windows" and env.msvc

# def is_platform(expected_value):
#     return "1" if env["platform"] == expected_value else "0"

javascript_engine = "v8" if is_v8_available() else "quickjs"

# env_jsb.Append(CPPDEFINES=["JSB_LOG_ENABLED=1"])

print("javascript engine:", javascript_engine)

# make these PreprocessorDefinitions publicly known for the convenience of IDE coding hints
javascript_shared_defines = [
    "JSB_WITH_V8="+         str(1 if javascript_engine == "v8" else 0),
    "JSB_WITH_QUICKJS="+    str(1 if javascript_engine == "quickjs" else 0),
    "JSB_WITH_DEBUGGER=0",
]

env_jsb = env_modules.Clone()

env.Append(CPPDEFINES=javascript_shared_defines)
env_jsb.Append(CPPDEFINES=javascript_shared_defines) # due to env_modules inherited from env before adding jsb preprocessors
module_obj = []

if javascript_engine == "v8":
    # it seems godot always links MT_StaticRelease even if env["dev_build"]
    # env.Append(LIBPATH=['v8/windows.x86_64.release'])
    if env["platform"] == "macos":
        env.Append(LIBS=[File("v8/macos.x64.release/libv8_monolith.a")])
    else:
        env.Append(LIBS=[File("v8/windows.x86_64.release/v8_monolith.lib")])
        env.Append(LINKFLAGS=["winmm.lib", "Dbghelp.lib"])

    if env["platform"] != "ios":
        env_jsb.AppendUnique(CPPDEFINES=["V8_COMPRESS_POINTERS"])

    env_jsb.Append(CPPDEFINES=["_ITERATOR_DEBUG_LEVEL=0"])
    env_jsb.add_source_files(module_obj, "bridge-v8/*.cpp")

    # env_jsb is enough for compiler, but IDE lookup paths from `env`
    if env.msvc and env["vsproj"]:
        env.Append(CPPPATH=["#modules/jsb/v8/include"])
    env_jsb.Append(CPPPATH=["v8/include"])
else:
    env_jsb.add_source_files(module_obj, "quickjs/*.c")
    env_jsb.add_source_files(module_obj, "bridge-quickjs/*.cpp")
    env_jsb.add_source_files(module_obj, "bridge-quickjs/extra/*.cpp")

# common parts
env_jsb.add_source_files(module_obj, ["register_types.cpp"])
env_jsb.add_source_files(module_obj, "internal/*.cpp")
env_jsb.add_source_files(module_obj, "weaver/*.cpp")

env.modules_sources += module_obj
